# Generated by Django 5.1.1 on 2024-09-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piechart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='stocks', max_length=100),
            preserve_default=False,
        ),
    ]
