# Generated by Django 5.1.1 on 2024-09-10 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('follow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='stocks', to=settings.AUTH_USER_MODEL),
        ),
    ]
