# Generated by Django 5.0.7 on 2024-08-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='earningsAnnouncement',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
