# Generated by Django 5.1.1 on 2024-09-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='pe',
            field=models.FloatField(blank=True),
        ),
    ]
