# Generated by Django 5.1.1 on 2024-09-09 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='user',
        ),
        migrations.AddField(
            model_name='stock',
            name='users',
            field=models.ManyToManyField(related_name='stocks', to=settings.AUTH_USER_MODEL),
        ),
    ]
