# Generated by Django 5.1.1 on 2024-09-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0003_remove_stock_user_stock_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='owned',
        ),
    ]
