# Generated by Django 5.0.7 on 2024-08-05 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('average_price', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follow.stock')),
            ],
        ),
    ]
