# Generated by Django 5.1.1 on 2024-09-13 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='timestamp',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('average_price', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.position')),
            ],
        ),
    ]
