# Generated by Django 5.0.7 on 2024-08-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_stock_position_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='symbol',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
