# Generated by Django 5.0.7 on 2024-08-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_position_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='symbol',
        ),
    ]
