# Generated by Django 5.1.1 on 2024-09-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_position_timestamp_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='average_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='quantity',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
