# Generated by Django 5.1.1 on 2024-09-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_position_portfolio_alter_position_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummyposition',
            name='stock',
            field=models.CharField(max_length=100),
        ),
    ]
