# Generated by Django 5.1.1 on 2024-12-25 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0004_alter_stock_pe'),
        ('portfolio', '0006_alter_dummyposition_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummyposition',
            name='user',
        ),
        migrations.RemoveField(
            model_name='position',
            name='user',
        ),
        migrations.AlterField(
            model_name='dummyposition',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='follow.stock'),
        ),
    ]
