# Generated by Django 5.0.7 on 2024-08-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_stock_data_stock_change_stock_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='change_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='high',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='latest_trading_day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='low',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='open_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='previous_close',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
