# Generated by Django 5.0.7 on 2024-08-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_stock_change_percent_stock_high_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='change_percent',
            new_name='changesPercentage',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='high',
            new_name='dayHigh',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='low',
            new_name='dayLow',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='open_price',
            new_name='open',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='previous_close',
            new_name='previousClose',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='latest_trading_day',
        ),
        migrations.AddField(
            model_name='stock',
            name='avgVolume',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='earningsAnnouncement',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='eps',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='exchange',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='marketCap',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='pe',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='priceAvg200',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='priceAvg50',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sharesOutstanding',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='timestamp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='yearHigh',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='yearLow',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
