# Generated by Django 5.0.7 on 2024-08-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_change_percent_stock_changespercentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('average_price', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='earningsAnnouncement',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
