# Generated by Django 5.0.7 on 2024-08-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_position_alter_stock_earningsannouncement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='quantity',
            field=models.FloatField(null=True),
        ),
    ]
