# Generated by Django 5.0.7 on 2024-08-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_position_average_price_alter_position_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='symbol',
        ),
    ]
