# Generated by Django 5.0.7 on 2024-08-05 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_position_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='Stock',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='api.stock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='followed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='owned',
            field=models.BooleanField(default=False),
        ),
    ]
